name: world_flags
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  device_info_plus: ^11.3.0
  flutter_svg: ^2.0.9
  google_mobile_ads: ^5.2.0
  firebase_core: 
  http: ^1.1.0
  shared_preferences: ^2.2.2
  vibration: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/flags_data.json

  